### PR TITLE
Add TypeScript typings

### PR DESCRIPTION
**Pull request by LinusU**
This adds TypeScript typings to the project, which not only makes it possible to use this product with TypeScript, but also provides a better editor experience for people writing JavaScript 🚀

### CODE REVIEW

**Comment by LinusU** [comment]
ping @silentcloud ☺️

**Comment by LinusU** [comment]
ping @silentcloud ☺️

**Comment by silentcloud** [comment]
Great job

**Comment by silentcloud** [comment]
1.1.2

**Comment by LinusU** [comment]
Thanks for the quick release! ❤️

**Pull request merged**
